export enum InvoiceStatus{
    PENDING ,
    PENDING_FOR_PAY,
    REJECT,
    PENDING_FOR_APPROVE_PAY,
    APPROVE_FOR_PAY,
    REJECT_FOR_PAY,
    CANCEL_BY_USER,
    PAY_CANCEL,
    ARRIVED_NOT_COMPELTE,
    ARRIVED_COMPELTE
}

